version: "3.5"

services:
  db:
    image: postgres:latest
    container_name: db
    env:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    options: >-
      --health-cmd pg_isready
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5
    ports:
      - 5432:5432
    networks:
      - sykinet

  back:
    image: docker.io/library/back
    container_name: back
    build:
      context: .
      dockerfile: Dockerfile.back
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DB_CONNECTION_STRING=Host=db;Username=postgres;Password=postgres;Port=5432;Database=rinha-db;Minimum Pool Size=10;Maximum Pool Size=10;Multiplexing=true;
    ports:
      - "8081:80"
    networks:
      - sykinet

networks:
  sykinet:
    driver: bridge
