name: app
version: 1.0.0+1
publish_to: 'none'
description: "Syki App"

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.8.0+1
  get_it: ^8.0.3
  provider: ^6.1.2
  go_router: ^14.8.0
  flutter_dotenv: ^5.2.1
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env.development
    - .env.production
    - assets/logos/
    - assets/icons/
    - assets/images/
