name: app
version: 1.0.0+1
publish_to: 'none'
description: "Syki"

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  dio: ^5.8.0+1
  logger: ^2.5.0
  flutter_dotenv: ^5.2.1
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env.development
    - .env.production
    - assets/logos/
    - assets/icons/
    - assets/images/onboarding/
