name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./Back/Back.csproj --configuration Release --no-build --output './publish'

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'syki-dev-api'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: './publish'
